// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // Amorce le premier compte ADMIN (voir prisma/seed.ts) via `npx prisma db seed`,
    // en remplacement de la création manuelle par Prisma Studio / SQL direct.
    seed: 'ts-node --transpile-only prisma/seed.ts',
  },
  datasource: {
    url:
      process.env['DATABASE_URL'] ??
      (() => {
        throw new Error('DATABASE_URL is not set in .env');
      })(),
  },
});